services:
 dashboard-vue-app:
    build: .
    ports:
      - "5175:5175"  # Menghubungkan port host dengan port di container
    environment:
      - HOST=0.0.0.0
      - PORT=5175
    volumes:
      - .:/app
      - /app/node_modules  # Pastikan node_modules tetap berada di container
