services:
  express-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    env_file:
      - .env  # Mengambil environment variables untuk express-backend
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - .env  # Mengambil environment variables untuk MySQL dari .env
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
