@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZkZDc1OWUxLTczMjUtNDFlNi04ZjNmLTUwOGU1YTVkOTVjZCIsInJvbGUiOiJjbGllbnQiLCJpYXQiOjE3Mjg2MzQ0MDcsImV4cCI6MTcyODk4MDAwN30.UXQz1SUl5kqxPpqAMshCI1ptigxFLSdnx8sv62osL-I

//login
###
POST http://localhost:5003/login
Content-Type: application/json

{
    "username" : "asep",
    "password" : "Diptya1234!"
}

//Create-Contact
###
POST http://localhost:5003/contact
Content-Type: application/json

{
    "firstName": "dicobamasulk",
    "lastName": "dicobamasulk",
    "emailAddress": "dicobamasulk@gmail.com",
    "message" : "masuk"
}

//register
###
POST http://localhost:5003/register
Content-Type: application/json

{
    "username": "asep", 
    "email":"jovanbryanginting@gmail.com", 
    "password":"Diptya1234!"
}

//verification-email
###
POST http://localhost:5003/verification-email
Content-Type: application/json

{
    "otp": "218316"
}

//reset-password
###
POST http://localhost:5003/reset-password
Content-Type: application/json

{
    "email": "diptyasoemantry@gmail.com"
}


//new-password
###
POST http://localhost:5003/new-password/{{token}}
Content-Type: application/json

{
    "newPassword": "MasukAja1234!"
}

//Verification Data Business
###
POST http://localhost:5003/verification-data
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "fullname": "Diptya Sumantry",
    "phone": "08123456789",
    "address": "JL. Kaliurang Km.14",
    "category_business": "Perbankan",
    "description_business": "Memberikan layanan tabungan dan pinjaman",
    "image": ""
}

//get-detail-verification
###
GET  http://localhost:5003/client-detail/fea3b69f-97d6-4e70-b564-318e7b36e6cc
Content-Type: application/json
Authorization: Bearer {{token}}

//get-detail-verification-Admin
###
GET  http://localhost:5003/client-detail/dasdas
Content-Type: application/json
Authorization: Bearer {{token}}

//Update-Client-detail
###
PUT http://localhost:5003/client-detail/f07be547-f310-436d-9e2a-4b1ec2f16bdc
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "fullname": "aser",
    "phone": "098765432133",
    "address": "jl.apel",
    "category_business": "asd",
    "description_business": "sad",
    "image": ""
}

//delete-Client-detail
###
DELETE http://localhost:5003/client-detail/f07be547-f310-436d-9e2a-4b1ec2f16bdc
Content-Type: application/json
Authorization: Bearer {{token}}

//detail client
###
GET  http://localhost:5003/clients
Content-Type: application/json
Authorization: Bearer {{token}}

//Update-Client
###
PUT http://localhost:5003/clients/6dd759e1-7325-41e6-8f3f-508e5a5d95cd
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "username" : "",
    "email" : "",
    "password" : "",
    "otp" : ""
}

//delete-Client
###
DELETE http://localhost:5003/clients/6dd759e1-7325-41e6-8f3f-508e5a5d95cd
Content-Type: application/json
Authorization: Bearer {{token}}

# {
#     "id" : "f07be547-f310-436d-9e2a-4b1ec2f16bdc"
# }

# //Get-User Managmenet
# ###
# GET http://localhost:5003/user-management
# Content-Type: application/json
# Authorization: Bearer {{token}}

# //Get-User Managmenet by ID
# ###
# GET http://localhost:5003/user-management/f0b13426-9a32-4f96-b89d-ccd086fee7c6
# Content-Type: application/json
# Authorization: Bearer {{token}}

# //Update-User Managmenet
# ###
# PUT http://localhost:5003/user-management/f0b13426-9a32-4f96-b89d-ccd086fee7c6
# Content-Type: application/json
# Authorization: Bearer {{token}}

# {
#     "username": "asep saefudin", 
#     "password": "Asep1234!ok", 
#     "role": "kasir", 
#     "fullname": "Asep Saeudin OKe mantap", 
#     "phone": "081234567831", 
#     "email": "asepjos@gmail.com"
# }

# //Delete-User Managmenet
# ###
# DELETE  http://localhost:5003/user-management/f0b13426-9a32-4f96-b89d-ccd086fee7c6
# Content-Type: application/json
# Authorization: Bearer {{token}}

# //create patient
# ###
# POST http://localhost:5003/patient
# Content-Type: application/json
# Authorization: Bearer {{token}}

# {
#     "fullname": "Bagus",
#     "place_birth": "Banyumas",
#     "date_birth": "2024-05-26",
#     "gender": "L",
#     "address": "sokaraja",
#     "work": "programer",
#     "phone": "08123456789",
#     "history_illness": "not-found",
#     "nik": "1234567890123456", 
#     "namaIbuKandung": "Sumantry",
#     "agama": "Islam",
#     "alamatKTP": "sokaraja",
#     "kecamatan": "sokaraja",
#     "kelurahan": "sokaraja",
#     "provinsi": "sokaraja",
#     "kota": "Banyumas",
#     "kodePos": "53181",
#     "rt": "3",
#     "rw": "1"
# }

# //GET PATIENT
# ###
# GET http://localhost:5003/patient?search=12345
# Authorization: Bearer {{token}}
# Content-Type: application/json

# //GET PATIENT DETAIL
# ###
# GET http://localhost:5003/patient/0586a16a-7fe0-4ea8-964a-a1d6c6f857bd
# Authorization: Bearer {{token}}
# Content-Type: application/json

# //UPDATE PATIENT
# ###
# PUT http://localhost:5003/patient/0586a16a-7fe0-4ea8-964a-a1d6c6f857bd
# Content-Type: application/json
# Authorization: Bearer {{token}}

# {
#     "fullname": "bagus",
#     "place_birth": "bagus",
#     "date_birth": "2023-02-13",
#     "gender": "L",
#     "address": "Banyumas",
#     "work": "student",
#     "phone": "01236470789",
#     "history_illness": "not-found",
#     "nik": "1234567890123471", 
#     "namaIbuKandung": "Sumantry",
#     "agama": "Islam",
#     "alamatKTP": "sokaraja",
#     "kecamatan": "sokaraja",
#     "kelurahan": "sokaraja",
#     "kota": "Banyumas",
#     "kodePos": "53181",
#     "rt": "3",
#     "rw": "1"
# }

# //CREATE REKAM MEDIS
# ###
# POST http://localhost:5003/rekam-medis
# Content-Type: application/json
# Authorization: Bearer {{token}}

# {
#     "date": "2024-05-26",
#     "diagnosis": "kepala pusing",
#     "therapy": "kurangi melihat cahaya",
#     "service": [{"name":"cabut gigi","price":"300000"},{"name":"Tambal Gigi","price":"500000"},{"name":"Pasang Behel","price":"400000"}],
#     "obat": [{"name": "bodrex", "price": "5000"}],
#     "bayar": 1205000,
#     "description": "istirahat yang cukup",
#     "odontogram": [
#         {
#           "oke": "masuk",
#           "sip": "ya"
#         },
#         {
#           "oke": "masuk",
#           "sip": "ya"
#         }
#       ],
#     "patient_id": "d454de95-5c87-4eed-9f7b-c0bb03927523",
#     "odontogram_gambar",
#     "namaKeluarga": "",
#     "jenisKelaminKeluarga": "",
#     "alamatKeluarga": "",
#     "telpKeluarga": "",
#     "statusInformContent": false
# }


# //GET ALL REKAM MEDIS
# ###
# GET http://localhost:5003/rekam-medis?page=&search=&sorting=&startDate=&endDate=
# Authorization: Bearer {{token}}
# Content-Type: application/json

# //GET ALL REKAM MEDIS
# ###
# GET http://localhost:5003/rekam-medis/patient/0586a16a-7fe0-4ea8-964a-a1d6c6f857bd
# Authorization: Bearer {{token}}
# Content-Type: application/json

# //GET DETAIL REKAM MEDIS
# ###
# GET http://localhost:5003/rekam-medis/9384181b-a490-402f-b36e-7d4cc484a8f4
# Authorization: Bearer {{token}}
# Content-Type: application/json

# //Koreksi Rekam Medis
# ###
# PUT http://localhost:5003/rekam-medis-koreksi/0435846a-cbf1-4bc8-8c86-95c7dab2c19e
# Authorization: Bearer {{token}}
# Content-Type: application/json

# {
#     "koreksi": "string"
# }

# //GET Invoice
# ###
# GET http://localhost:5003/invoice?page=&search=&sorting=&invoiceId=&startDate=&endDate=&patientId=
# Authorization: Bearer {{token}}
# Content-Type: application/json

# //GET Wilayah
# ###
# GET http://localhost:5003/wilayah?kodeProvinsi=33&kodeKota=33.02&kodeKecamatan=33.02.26
# Authorization: Bearer {{token}}
# Content-Type: application/json

# //UPDATE Invoice
# ###
# PUT  http://localhost:5003/invoice/c489d23b-e7cf-4566-a258-81832077bf3a
# Authorization: Bearer {{token}}
# Content-Type: application/json

# {
#     "bayar": 1200000
# }

# //Dashboard
# ###
# GET http://localhost:5003/dashboard
# Authorization: Bearer {{token}}
# Content-Type: application/json

# //LAYANAN
# //CREATE layanan
# ###
# POST http://localhost:5003/layanan
# Content-Type: application/json
# Authorization: Bearer {{token}}

# {
#     "name": "Gigi Bolong",
#     "price": "10000",
#     "code": "tmblong"
# }

# //GET ALL layanan
# // search name and code
# // sorting ASC or DESC from name
# ###
# GET http://localhost:5003/layanan?page=&search=&sorting=
# Authorization: Bearer {{token}}
# Content-Type: application/json

# //Update layanan
# ###
# PUT http://localhost:5003/layanan/b243312d-b733-4bd3-9015-2507344ea3ee
# Content-Type: application/json
# Authorization: Bearer {{token}}

# {
#     "name": "Cabut Gigi",
#     "price": "15000",
#     "code": "Cbt"
# }

# //GET DETAIL layanan
# ###
# GET http://localhost:5003/layanan/b243312d-b733-4bd3-9015-2507344ea3ee
# Authorization: Bearer {{token}}
# Content-Type: application/json

# //Delete  layanan
# ###
# DELETE  http://localhost:5003/layanan/b243312d-b733-4bd3-9015-2507344ea3ee
# Authorization: Bearer {{token}}
# Content-Type: application/json

# //CREATE Obat
# ###
# POST http://localhost:5003/obat
# Content-Type: application/json
# Authorization: Bearer {{token}}

# {
#     "code": "BDRX",
#     "name": "Bodrex",
#     "price": "10000"
# }

# //GET ALL OBAT
# // search name and code
# // sorting ASC or DESC from name
# ###
# GET http://localhost:5003/obat?page=&search=&sorting=
# Authorization: Bearer {{token}}
# Content-Type: application/json

# //Update Obat
# ###
# PUT http://localhost:5003/obat/d32972e3-de73-4843-9a37-b51a9c375e95
# Content-Type: application/json
# Authorization: Bearer {{token}}

# {
#     "name": "Bodrex C",
#     "price": "15000",
#     "code": "BDRX z"
# }

# //GET DETAIL OBAT
# ###
# GET http://localhost:5003/obat/d32972e3-de73-4843-9a37-b51a9c375e95
# Authorization: Bearer {{token}}
# Content-Type: application/json

# //DELETE OBAT
# ###
# DELETE  http://localhost:5003/obat/5734ee71-9bb9-4d82-90ac-cd5858d8810a
# Authorization: Bearer {{token}}
# Content-Type: application/json

# //List kunjungan patient to dashbaord
# ###
# GET http://localhost:5003/list-kunjungan
# Authorization: Bearer {{token}}
# Content-Type: application/json